### PR TITLE
make Package.resolved tracking

### PR DESCRIPTION
**Pull request by zunda-pixel**
[Dependabot](https://github.com/dependabot) needs Package.resolved
https://github.blog/changelog/2023-08-01-swift-support-for-dependabot-updates/

### CODE REVIEW

**Comment by FranzBusch** [comment]
We don't commit the `Package.resolved` in any of our library repos since it has potential negative consequences on local development and CI building. In my opinion, this is an open enhancement on the Dependabot side which should be able to use the `Package.swift` itself. cc @0xTim

**Comment by 0xTim** [comment]
Dependabot currently does not support detecting dependencies from the Package.swift file but there's an argument to be made about what exactly it should try and do with that information in a library? There's not really anything to update because that's on the integrator's side.

There is a mechanism for providing package metadata via the dependency submission API which is something we should probably support and could be built as a GH action and shared across any Swift repo. We (Vapor) have looked into this but don't think we have anything to share at this time

**Comment by zunda-pixel** [comment]
Dependabots is useful for auto creating update library pull requests.
But Apple' repository has unique CI, and Package.resolved is not needed for it.
We don't have to have `Package.resolved` for now?

**Comment by FranzBusch** [comment]
> But Apple' repository has unique CI, and Package.resolved is not needed for it.
> We don't have to have `Package.resolved` for now?

It's not so much about unique CI but rather that updating dependencies in packages that offer library products is irrelevant. If we were to commit a `Package.resolved` file here it would only impact our local development and our CI but not the downstream consumers of this package. So yes, I don't think we should commit the resolved file.

**Pull request closed without merging**
